### PR TITLE
Better outing's edition form

### LINKED ISSUE #957: Incorrect georef of outings
When creating an outing, it may happen that users click on the map by mistake (eg. scrolling the page). This results in adding a georef to the outing that is totally incorrect.

An improvement must be found to avoid this. For instance by moving the map to its own section?

### PR DESCRIPTION
**Pull request by cbeauchesne**
Fixes #957, #1981 and #1980 

image

### CODE REVIEW

**Comment by brunobesson** [comment]
Picture? 🥺

**Comment by cbeauchesne** [comment]
It's very early, I'm not yes sure what's the best way to do this.

**Comment by cbeauchesne** [comment]
FYI, I've started a feedback thread on forum: https://forum.camptocamp.org/t/amelioration-du-formulaire-de-sorties/281231

I'll set this PR. "ready for review" once i've finished with comments form users.

**Comment by cbeauchesne** [comment]
Fixes ##957 and #1980 

Ready for review !

File: src/views/wiki/edition/OutingEditionView.vue [hunk 1]
```diff
@@ -190,18 +237,168 @@ export default {
...
+        this.$nextTick(this.fitMapToDocuments);
+      }
+    },
+
+    changeRouteAssociation(addRoute, route) {
+      if (!addRoute && !this.routeIsAssociated(route.document_id)) {
+        return;
+      } else if (addRoute && this.routeIsAssociated(route.document_id)) {
+        return;
+      }
```
Comment (brunobesson) [inline src/views/wiki/edition/OutingEditionView.vue:369]: group in one

File: src/views/wiki/edition/OutingEditionView.vue [hunk 2]
```diff
@@ -190,18 +237,168 @@ export default {
...
+            this.fitMapToDocuments();
+            this.updateRoutes('First route', false);
+          });
+        } else {
+          this.$documentUtils.propagateProperties(this.document, route);
+        }
+      } else {
+        this.document.associations.routes = routes.filter((r) => r.document_id !== route.document_id);
+
+        if (this.document.associations.routes.length === 0) {
```
Comment (brunobesson) [inline src/views/wiki/edition/OutingEditionView.vue:391]:
```suggestion
        if (!this.document.associations.routes.length) {
```

**Review by brunobesson — COMMENTED** [review]
Some comments on ergonomics, still:
* do we want to display the routes geom in map? As there is no interaction, what's the use?
* some more already explicited. but it's a first step, we can build on it

File: src/views/document/utils/boxes/RecentOutingsBox.vue [hunk 3]
```diff
@@ -55,9 +55,28 @@ export default {
...
+    showAddOutingButton() {
+      if (this.documentType === 'route') {
+        return true;
+      }
+
+      if (this.documentType === 'waypoint' && this.document.associations.all_routes.total !== 0) {
+        return true;
+      }
+
+      return false;
```
[the remark this answers is not in the document]
Comment (cbeauchesne) [reply src/views/document/utils/boxes/RecentOutingsBox.vue]: For this kind of logic, I feel that a `if` for each case is better, because more explicit. I've added a comment on each case.

File: src/components/map/OlMap.vue [hunk 4]
```diff
@@ -471,23 +481,12 @@ export default {
         'addfeatures',
         function (event) {
           event.features.map(this.setDocumentGeometryFromFeature);
-          this.fitMapToDocuments(true);
```
[the remark this answers is not in the document]
Comment (cbeauchesne) [reply src/components/map/OlMap.vue:474]: It is, with a watcher on `document.geometry.geom_detail` in outingEdition component.

I've cleaned the event logic role here : 

1. Except for the very first display, the map component by itself do not decide to refit the map. The use cases to decide to refit or not are too complicated to be in this component, so it's up to the parent component to decide o refit or not.
2. The only use case when the map component refit itself is only when the user decide to do so.

Though, I forgot to add it on route, when the point is set, but not the trace. thank's !

File: src/views/wiki/edition/OutingEditionView.vue [hunk 5]
```diff
@@ -23,12 +24,56 @@
...
+
+      <div v-if="possibleRoutes && possibleRoutes.length !== 0" class="field">
+        <div v-for="route of possibleRoutes" :key="route.document_id">
+          <input-checkbox :value="routeIsAssociated(route.document_id)" @input="changeRouteAssociation($event, route)">
+            <activities :activities="route.activities" class="is-size-4 has-text-secondary" />
+            <document-title :document="route" />,
+            <document-rating :document="route" />
+          </input-checkbox>
+          <document-link :document="route" target="_blank">
+            <fa-icon icon="link" />
```
[the remark this answers is not in the document]
Comment (cbeauchesne) [reply src/views/wiki/edition/OutingEditionView.vue:61]: I've added a title.

File: src/views/wiki/edition/OutingEditionView.vue [hunk 6]
```diff
@@ -23,12 +24,56 @@
...
+          {{ $gettext('routes') | uppercaseFirstLetter }}:
+          <marker-helper name="1063027#routes" />
+        </label>
+        <div class="control">
+          <input class="input" type="text" placeholder="Name" v-model="routeTitle" />
+        </div>
+      </div>
+
+      <div v-if="possibleRoutes && possibleRoutes.length !== 0" class="field">
+        <div v-for="route of possibleRoutes" :key="route.document_id">
```
[the remark this answers is not in the document]
Comment (cbeauchesne) [reply src/views/wiki/edition/OutingEditionView.vue:54]: So do I :)

Let's start if this, and see users' feedback

File: src/views/wiki/edition/OutingEditionView.vue (hunk 2 above)
Comment (cbeauchesne) [reply src/views/wiki/edition/OutingEditionView.vue]: Done. 

Though, could you explain why the second line is better? I really feel that the first one is much more clear, and if there is a performance issue, it should be negligible for a line executed only once, no?

Actually, if it's a good practice to use boolean operator instead of `===0`, we should consider implementing it in the linter, it'll save some time and energy for PR.

**Comment by cbeauchesne** [comment]
Thank's for the review!

> do we want to display the routes geom in map? As there is no interaction, what's the use?

I've been a little bit lazy (or a gentle way to rephrase: I didn't want to do huge PR :) ) I plan to add an title on those icon, and use them as a link, or a selector, don't know yet the best usage.

**Comment by brunobesson** [comment]
> I plan to add an title on those icon, and use them as a link, or a selector, don't know yet the best usage.

Beware, it's complicated to be able to click on such feature in map and open it in a new tab in a native browser way (i.e. click opens in place, ctrl+click or middle mouse click opens in tab or new window). If you want to force to open in blank target, should be doable though.

If you intend to keep the feature in the map, maybe they should have a specific style, to be easily distinguishable.

File: src/js/vue-plugins/document-utils.js [hunk 7]
```diff
@@ -149,11 +149,11 @@ export default function install(Vue) {
...
           this.propagateRoutePropertiesToOutingProperties(child, parent);
-        } else if (parent.type === 'r' && child.type === 'w') {
-          this.propagateGeomPoint(child, parent);
-        } else if (parent.type === 'x' && child.type === 'r') {
-          this.propagateGeomPoint(child, parent);
-        } else if (parent.type === 'x' && child.type === 'o') {
+        } else if (
+          (parent.type === 'r' && child.type === 'w') ||
+          (parent.type === 'x' && child.type === 'r') ||
+          (parent.type === 'x' && child.type === 'o')
```
Comment (brunobesson) [inline src/js/vue-plugins/document-utils.js:155]: parentheses are useless because of operator priority. (unless prettier does a bad job at splitting?)

File: src/js/vue-plugins/document-utils.js [hunk 8]
```diff
@@ -343,7 +343,11 @@ export default function install(Vue) {
       },
 
       getDocumentsBbox(documents) {
-        // given an array of documents, return the extent containing all these documents
+        documents = documents.filter((document) => document?.geometry?.geom);
```
Comment (brunobesson) [inline src/js/vue-plugins/document-utils.js:346]: `document` can be undefined too? maybe you are using too many question marks there 🙂

File: src/views/wiki/edition/OutingEditionView.vue [hunk 9]
```diff
@@ -57,7 +57,7 @@
             <document-title :document="route" />,
             <document-rating :document="route" />
           </input-checkbox>
-          <document-link :document="route" target="_blank">
+          <document-link :document="route" target="_blank" :title="$gettext('Open in a new tab')">
```
Comment (brunobesson) [inline src/views/wiki/edition/OutingEditionView.vue:60]: Depending on the browser configuration, I do think it can be a new tab or a new window (although few people use the latter option, I think)

File: src/views/wiki/edition/RouteEditionView.vue [hunk 10]
```diff
@@ -194,6 +189,14 @@ export default {
       }
     },
 
+    onGeometryUpdate(to, from) {
```
Comment (brunobesson) [inline src/views/wiki/edition/RouteEditionView.vue:192]: forgot this earlier, but this method is used in many edition views. Could be put in a mixin?

File: src/js/vue-plugins/document-utils.js (hunk 7 above)
Comment (cbeauchesne) [reply src/js/vue-plugins/document-utils.js:155]: Nope, prettier add them.

**Comment by cbeauchesne** [comment]
@b_b, all good on my side

**Review by brunobesson — APPROVED** [review]

**Comment by brunobesson** [comment]
Could we consider it fixes #819 too?

**Comment by cbeauchesne** [comment]
Definitely, good catch!
